name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install Node.js
        # You may pin to the exact commit or the version.
        # uses: xRealNeon/VuePagesAction@803b88b34a8c4177efad63425155f35419e3a9c6
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '14.X'
      - name: install dep
        run: npm install
      - name: build app
        run: npm build
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          source: 'dist/'
          port: 22
          target: ${{ secrets.REMOTE_TARGET }}
